#!/bin/sh
module="uio48"
device="uio48"
mode="666"
io_addr="0x120"
irq_num="10"


# Group: since distributions do it differently, look for wheel or use staff
if grep '^staff:' /etc/group > /dev/null; then
    group="staff"
else
    group="wheel"
fi

# invoke modprobe with all arguments
/sbin/modprobe $module io_port=$io_addr irq=$irq_num


chgrp $group /dev/${device}a
chmod $mode  /dev/${device}a
